/**
 * Loop / autoresponder / bounce detection for inbound email (D28d).
 *
 * Pure function — no DB, no IMAP. Decides whether the email should be
 * rejected before any ticket-creation work happens. A return of `null`
 * means "proceed to threading"; anything else is the reason for rejection
 * and writes to inbound_email_log.status.
 *
 * Adopted full set:
 *   - RFC 3834 (Auto-Submitted, Precedence, X-Precedence)
 *   - osTicket vendor autoresponder markers
 *   - Bounce / DSN signals (MAILER-DAEMON, Return-Path: <>, multipart/report)
 *   - Self-loop signals (own ingest mailbox in From, own host + Precedence: bulk)
 *
 * Threading body/attachment scanning is deliberately NOT done here (Zammad
 * does it; that's a documented info-disclosure surface).
 */

export type LoopRejection =
  | { status: 'rejected_autoresponder'; reason: string }
  | { status: 'rejected_bounce'; reason: string }
  | { status: 'rejected_loop'; reason: string }

export interface LoopDetectionInput {
  headers: Record<string, string | string[] | undefined>
  fromAddress: string | null
  toAddresses: string[]
  subject: string | null
  contentType: string | null
  /** The mailbox we polled — case-insensitive comparison against From for self-loop. */
  ingestMailbox: string
  /** Configured outbound message_id host — case-insensitive comparison for self-host loop. */
  outboundHost: string | null
  /** Reply-to address used in our outbound — used for X-Loop self-detection. */
  replyAddress: string | null
}

/**
 * Returns the rejection reason or `null` if the email passes loop detection.
 */
export function detectLoop(input: LoopDetectionInput): LoopRejection | null {
  const h = (name: string): string | null => {
    const v = input.headers[name.toLowerCase()]
    if (Array.isArray(v)) return v[0] ?? null
    return typeof v === 'string' ? v : null
  }

  // ----- RFC 3834 / Precedence ------------------------------------------------
  const autoSubmitted = h('Auto-Submitted')?.toLowerCase().split(';')[0]?.trim()
  if (
    autoSubmitted &&
    ['auto-replied', 'auto-generated', 'auto-notified'].includes(autoSubmitted)
  ) {
    return { status: 'rejected_autoresponder', reason: `Auto-Submitted: ${autoSubmitted}` }
  }

  const precedence = h('Precedence')?.toLowerCase().trim()
  if (precedence && ['auto_reply', 'bulk', 'junk', 'list'].includes(precedence)) {
    return { status: 'rejected_autoresponder', reason: `Precedence: ${precedence}` }
  }
  if (h('X-Precedence')) {
    return { status: 'rejected_autoresponder', reason: 'X-Precedence header present' }
  }

  // ----- Vendor autoresponder markers (osTicket) ------------------------------
  const vendorAutoreplyHeaders = [
    'X-Autoreply',
    'X-Auto-Response-Suppress',
    'X-Autoresponse',
    'X-AutoReply-From',
    'X-Autorespond',
    'X-Mail-Autoreply',
    'X-Autogenerated',
  ]
  for (const name of vendorAutoreplyHeaders) {
    if (h(name)) {
      return { status: 'rejected_autoresponder', reason: `${name} header present` }
    }
  }

  if (h('X-AMAZON-MAIL-RELAY-TYPE')?.toUpperCase() === 'NOTIFICATION') {
    return { status: 'rejected_autoresponder', reason: 'X-AMAZON-MAIL-RELAY-TYPE: NOTIFICATION' }
  }

  // ----- Bounce / DSN ---------------------------------------------------------
  const fromLower = (input.fromAddress || '').toLowerCase()
  if (fromLower === '' || /^(mailer-daemon|postmaster)@/.test(fromLower)) {
    return { status: 'rejected_bounce', reason: `From: ${input.fromAddress || '(empty)'}` }
  }

  const returnPath = h('Return-Path')?.trim()
  if (returnPath === '<>' || returnPath === '<MAILER-DAEMON>') {
    return { status: 'rejected_bounce', reason: `Return-Path: ${returnPath}` }
  }

  if (h('X-Failed-Recipients')) {
    return { status: 'rejected_bounce', reason: 'X-Failed-Recipients header present' }
  }

  if (input.contentType) {
    const ct = input.contentType.toLowerCase()
    if (ct.includes('multipart/report') && /report-type\s*=\s*"?delivery-status/i.test(ct)) {
      return { status: 'rejected_bounce', reason: 'multipart/report; report-type=delivery-status' }
    }
  }

  if (
    input.subject &&
    /(delivery (failure|status notification|failed)|undeliverable|undelivered mail)/i.test(
      input.subject,
    )
  ) {
    return { status: 'rejected_bounce', reason: `Subject pattern: ${input.subject.slice(0, 80)}` }
  }

  // ----- Self-loop ------------------------------------------------------------
  const ingestLower = input.ingestMailbox.toLowerCase()
  if (fromLower && fromLower === ingestLower) {
    return { status: 'rejected_loop', reason: 'From == ingest mailbox' }
  }
  if (input.toAddresses.some(t => t.toLowerCase() === ingestLower) === false &&
      fromLower === ingestLower) {
    // belt-and-suspenders — should be caught above, leaving the explicit branch
    return { status: 'rejected_loop', reason: 'From == ingest mailbox' }
  }

  // X-Loop self-detection (we set X-Loop on outbound per D28e)
  if (input.replyAddress) {
    const xLoop = h('X-Loop')?.toLowerCase().trim()
    if (xLoop && xLoop === input.replyAddress.toLowerCase()) {
      return { status: 'rejected_loop', reason: 'X-Loop matches our outbound reply address' }
    }
  }

  // Domain match + Precedence: bulk (Zammad pattern, narrow self-loop signal)
  if (input.outboundHost && fromLower) {
    const fromDomain = fromLower.split('@')[1]
    if (
      fromDomain &&
      fromDomain === input.outboundHost.toLowerCase() &&
      precedence === 'bulk'
    ) {
      return {
        status: 'rejected_loop',
        reason: `From domain matches outbound host with Precedence: bulk`,
      }
    }
  }

  return null
}
