import { describe, expect, it } from 'vitest'
import { detectLoop, type LoopDetectionInput } from './loop-detection'

const SUPPORT = 'support@example.com'
const REPLY_ADDR = 'replies@aegis.example.com'

function input(overrides: Partial<LoopDetectionInput>): LoopDetectionInput {
  return {
    headers: {},
    fromAddress: 'user@example.org',
    toAddresses: [SUPPORT],
    subject: 'Hello',
    contentType: 'text/plain',
    ingestMailbox: SUPPORT,
    outboundHost: null,
    replyAddress: REPLY_ADDR,
    ...overrides,
  }
}

describe('detectLoop — passes a normal email through', () => {
  it('returns null for plain user mail', () => {
    expect(detectLoop(input({}))).toBeNull()
  })
})

describe('detectLoop — RFC 3834 / Precedence', () => {
  it.each([
    ['auto-replied'],
    ['auto-generated'],
    ['auto-notified'],
  ])('Auto-Submitted: %s → rejected_autoresponder', (val) => {
    const r = detectLoop(input({ headers: { 'auto-submitted': val } }))
    expect(r?.status).toBe('rejected_autoresponder')
    expect(r?.reason).toContain(val)
  })

  it('Auto-Submitted: no (the legitimate non-auto value) does NOT reject', () => {
    expect(detectLoop(input({ headers: { 'auto-submitted': 'no' } }))).toBeNull()
  })

  it.each([['auto_reply'], ['bulk'], ['junk'], ['list']])(
    'Precedence: %s → rejected_autoresponder',
    (val) => {
      const r = detectLoop(input({ headers: { precedence: val } }))
      expect(r?.status).toBe('rejected_autoresponder')
    },
  )

  it('X-Precedence (any value) → rejected_autoresponder', () => {
    const r = detectLoop(input({ headers: { 'x-precedence': 'whatever' } }))
    expect(r?.status).toBe('rejected_autoresponder')
  })
})

describe('detectLoop — vendor autoresponder markers', () => {
  it.each([
    ['x-autoreply'],
    ['x-auto-response-suppress'],
    ['x-autoresponse'],
    ['x-autoreply-from'],
    ['x-autorespond'],
    ['x-mail-autoreply'],
    ['x-autogenerated'],
  ])('%s → rejected_autoresponder', (header) => {
    const r = detectLoop(input({ headers: { [header]: 'present' } }))
    expect(r?.status).toBe('rejected_autoresponder')
  })

  it('X-AMAZON-MAIL-RELAY-TYPE: NOTIFICATION → rejected_autoresponder', () => {
    const r = detectLoop(
      input({ headers: { 'x-amazon-mail-relay-type': 'NOTIFICATION' } }),
    )
    expect(r?.status).toBe('rejected_autoresponder')
  })

  it('X-AMAZON-MAIL-RELAY-TYPE: TRANSACTIONAL is NOT rejected', () => {
    expect(
      detectLoop(input({ headers: { 'x-amazon-mail-relay-type': 'TRANSACTIONAL' } })),
    ).toBeNull()
  })
})

describe('detectLoop — bounces / DSN', () => {
  it('From: MAILER-DAEMON@... → rejected_bounce', () => {
    const r = detectLoop(input({ fromAddress: 'MAILER-DAEMON@mta.example.com' }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('From: postmaster@... → rejected_bounce', () => {
    const r = detectLoop(input({ fromAddress: 'postmaster@mta.example.com' }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('Empty From: → rejected_bounce', () => {
    const r = detectLoop(input({ fromAddress: '' }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('Return-Path: <> → rejected_bounce', () => {
    const r = detectLoop(input({ headers: { 'return-path': '<>' } }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('X-Failed-Recipients header → rejected_bounce', () => {
    const r = detectLoop(input({ headers: { 'x-failed-recipients': 'foo@bar.com' } }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('multipart/report; report-type=delivery-status → rejected_bounce', () => {
    const r = detectLoop(
      input({ contentType: 'multipart/report; report-type=delivery-status; boundary=xyz' }),
    )
    expect(r?.status).toBe('rejected_bounce')
  })

  it.each([
    ['Delivery Status Notification (Failure)'],
    ['Undeliverable: Original Subject'],
    ['Undelivered Mail Returned to Sender'],
    ['Delivery failure'],
  ])('Subject %j → rejected_bounce', (subject) => {
    const r = detectLoop(input({ subject }))
    expect(r?.status).toBe('rejected_bounce')
  })

  it('Normal subject does NOT match bounce pattern', () => {
    expect(detectLoop(input({ subject: 'Question about my undelivered package' }))).toBeNull()
    // Subject contains "undelivered" but as part of "package" — pattern is
    // "undelivered mail" specifically, so this should NOT match.
  })
})

describe('detectLoop — self-loop', () => {
  it('From == ingest mailbox → rejected_loop', () => {
    const r = detectLoop(input({ fromAddress: SUPPORT }))
    expect(r?.status).toBe('rejected_loop')
  })

  it('X-Loop matches our reply address → rejected_loop', () => {
    const r = detectLoop(input({ headers: { 'x-loop': REPLY_ADDR } }))
    expect(r?.status).toBe('rejected_loop')
  })

  it('From-domain matches outbound host with Precedence: bulk → rejected_loop', () => {
    const r = detectLoop(
      input({
        fromAddress: 'noise@aegis.example.com',
        headers: { precedence: 'bulk' },
        outboundHost: 'aegis.example.com',
      }),
    )
    // The precedence:bulk check trips first (rejected_autoresponder), so
    // the more specific self-host check is rarely the trigger. Either way,
    // the email must be rejected.
    expect(r).not.toBeNull()
  })

  it('Different domain with Precedence: bulk → rejected via precedence (not self-host)', () => {
    const r = detectLoop(
      input({
        fromAddress: 'noise@other.com',
        headers: { precedence: 'bulk' },
        outboundHost: 'aegis.example.com',
      }),
    )
    expect(r?.status).toBe('rejected_autoresponder')
  })
})
