import { auth } from '@/lib/auth'
import { pool } from '@/lib/db'
import { getOrgId } from '@/lib/org'
import { NextRequest, NextResponse } from 'next/server'

const DEFAULT_TEXT = 'Responses are generated by AI and may not always be accurate. Your IT team can review conversations.'

/**
 * GET /api/portal/ai-disclaimer
 * Returns the AI chat disclaimer config for the current org.
 * Any authenticated user can call this.
 */
export async function GET(request: NextRequest) {
  try {
    const session = await auth.api.getSession({ headers: request.headers })
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const orgId = await getOrgId()

    const result = await pool.query(
      `SELECT key, value FROM site_settings
       WHERE organization_id = $1 AND key IN ('ai_chat_disclaimer_enabled', 'ai_chat_disclaimer_text')`,
      [orgId]
    )

    const settings: Record<string, string> = {}
    for (const row of result.rows) {
      settings[row.key] = row.value
    }

    const enabled = settings.ai_chat_disclaimer_enabled !== 'false'
    const text = settings.ai_chat_disclaimer_text || DEFAULT_TEXT

    return NextResponse.json({ enabled, text })
  } catch (error) {
    console.error('Error fetching AI disclaimer:', error)
    return NextResponse.json({ enabled: true, text: DEFAULT_TEXT })
  }
}
